### PR TITLE
Fixes for Quill 2.0

### PR DESCRIPTION
**Pull request by artknight**

### CODE REVIEW

**Comment by artknight** [comment]
weird, running `npm run test` locally runs just fine.

**Comment by artknight** [comment]
As soon as @MadSpindel reviews the changes, I will merge it.

**Comment by artknight** [comment]
If noone reviews this by tomorrow morning, I am going to just merge it :)

**Comment by MadSpindel** [comment]
Is it possible to split this up into different PRs? It's hard to review this since you have also made formatting changes.

If you could first make just the changes needed for Quill 2.0, then another PR for formatting changes.

**Review by MadSpindel — CHANGES_REQUESTED** [review]
Is it possible to split this up into different PRs? It's hard to review this since you have also made formatting changes.

If you could first make just the changes needed for Quill 2.0, then another PR for formatting changes.

**Comment by artknight** [comment]
Unfortunately I do not have time split up the PR into smaller chunks. This PR was a curtesy (asked by many users) to port all the changes from my cloned repo into here. TBH, I could have merged it already but I wanted someone from this team to look over the code logic. It does not have that many changes anyway for you not be able to spend a minute to look over.

So, this is it.. i am afraid.

**Comment by artknight** [comment]
You could just ignore the whole `/dist` folder and just focus on the `/src`.

**Comment by dan-bartlettroofs** [comment]
> Unfortunately I do not have time split up the PR into smaller chunks. This PR was a curtesy (asked by many users) to port all the changes from my cloned repo into here. TBH, I could have merged it already but I wanted someone from this team to look over the code logic. It does not have that many changes anyway for you not be able to spend a minute to look over.
> 
> So, this is it.. i am afraid.

This is why the PR I submit was much smaller than this. I spent the time reverting formatting changes and tried to find the pieces and parts that made the difference. I agree it is time consuming.

**Comment by artknight** [comment]
@MadSpindel it seems all my changes are there. I do feel pretty confident about merging it b/c I am using the code in production already - https://cogency.io.

**Comment by artknight** [comment]
@MadSpindel I did not realize you were going to revert my merge! Why? 

The other PR I examined did have my JS changes, but not the CSS fixes. So now master is half-broken! 

PS: Since my PR contained all those changes, and some... you should have just closed #375 without merging.

**Comment by artknight** [comment]
@MadSpindel there were a bunch of CSS changes that addressed existing, and new issues that came with the v2 upgrade. I have been using my code in production, as mentioned, which should make it `safe` to merge. Besides, you told me to merge my changes in. If you are not going to bring the state of the plugin to the most reliable level, I will resolve using my cloned repo for any future updates, which will just take users away from your repo. It is up to you!

**Comment by csculley** [comment]
For the future, we should be able to restrict PRs from being merged in until they get an approval by requiring these options and making sure `master` is protected

**Comment by omgoshjosh** [comment]
Hello! Great library. Did the CSS fixes from this PR get into master anywhere, were those fixes unnecessary, are they in progress somewhere, or is this issue not big enough right now for the community/repo owner(s) to do something about? as i understand it, artknight has what he needs deployed for himself and running in production, but what issues are now unresolved by the CSS fixes that were reverted?

**Comment by artknight** [comment]
I still don't quite understand why my PR was reverted, despite of being asked to create it in the first place. I did sync up the latest JS changes that are working fine. I did not update the CSS, as I am a little worried it might re-introduce issues I had fixed already.

**Comment by MadSpindel** [comment]
@omgoshjosh I think #389 is needed, but I don't have the time to look into it.

**Pull request merged**
