### PR TITLE
show mention list on mention item click

### PR DESCRIPTION
**Pull request by rajshivam**
Click on mention embed in the quill editor reopens the mention list.
Edit feature for mention list.

### CODE REVIEW

**Comment by komxvl** [comment]
Dear @MadSpindel please merge this PR. Thnx.

**Comment by rajshivam** [comment]
@MadSpindel Yeah, that is a better implementation.
I've implemented the same.
Thanks.

**Comment by MadSpindel** [comment]
Is it possible to remove the mention if you type something? Now it only works with default suggestions?

**Comment by rajshivam** [comment]
Yes, if you do not select the mention item, mention list container will disappear. It will work as it did before, I've not modified that part.

**Comment by MadSpindel** [comment]
What I mean is like this;

1. Click on existing mention
2. If you type anything, the selected mention is removed and replaced with `@` and you can search for whatever you want.

Is it possible to make it work like that?

**Comment by rajshivam** [comment]
This will work in case showDenotationChar is true, else we'll have to keep an index of all mention characters. 
Currently upon clicking existing mention, mention list opens up and selecting any item in the list changes the mention.
If one wants to remove a mention, there is no need to click on it, delete or backspace does the job.

**Comment by iamshouvikmitra** [comment]
Any updates on this feature?

**Pull request closed without merging**
