### PR TITLE
Artknight changes

### PR DESCRIPTION
**Pull request by dan-bartlettroofs**
Hey All, New here!

I was previously building my own editable div in Vue to create mentions. This project, quill-mention, and quill is going to save me a ton of time. So, testing it out I could get the previous version to work great but I really wanted Quill 2.0.0. 

I saw @artknight had a version working on dev.3 or dev.4. So, I snagged his code and started checking the differences. I was able to build this and link it to my project and it seems to solve the errors I was getting from the previous version.

Beyond changing the quill version and scanning @artknight 's version I didn't attempt to make any other changes. I hope this helps everyone and especially @artknight get his changes merged in in a timely manor! 

Thanks so much for sharing this great module. 
Forgive me for bad etiquette or if this was a waste of everyone's time!

### CODE REVIEW

**Comment by csculley** [comment]
These changes look great! Unfortunately it seems like Prettier needs to run, could you do `npm run lint` to format the changes? Thank you!

**Comment by csculley** [comment]
Seems like this would close #362, #363 and #344.
It might also close #361, but we should check to make sure none of those issues are present before merging this in

**Comment by dan-bartlettroofs** [comment]
> These changes look great! Unfortunately it seems like Prettier needs to run, could you do `npm run lint` to format the changes? Thank you!

Ran that command and pushed changes!

**Comment by dan-bartlettroofs** [comment]
> Seems like this would close #362, #363 and #344. It might also close #361, but we should check to make sure none of those issues are present before merging this in

As far as #361 I did notice the "After Selecting a value from dropdown and hitting enter is adding a new line in editor instead of inserting an embed" issue and @artknight 's change in this PR fixed it for me. 

I don't want credit for any of this and I do hope @artknight is able to PR for themselves. Just trying to help out.

**Pull request merged**
