### PR TITLE
Enforces prettier

### PR DESCRIPTION
**Pull request by csculley**
I noticed that while prettier was installed and configured, it wasn't enforced in the project. This PR adds/modifies some scripts:

- `npm run lint`: to format all code with prettier
- `npm run test`: now checks with prettier before running tests

In addition, this adds a Github action that will run for Pull Requests, which can be set as required to merge in PRs. It may be easier to review this PR by commit rather than by diff. Once this is merged in, we will need to add `test` to the required status conditions in the branch protection settings.

Please let me know if anything should be changed. Thank you!

### CODE REVIEW

**Review by MadSpindel — APPROVED** [review]
LGTM

**Comment by csculley** [comment]
@MadSpindel Thank you! I'm not exactly sure who has maintainer status, but could you also add `test` as a required status check in the branch protection settings? Afaik, just checking the "require status checks" option doesn't actually block PRs if it fails

**Review by thexeos — COMMENTED** [review]
LGTM

**Comment by MadSpindel** [comment]
> @MadSpindel Thank you! I'm not exactly sure who has maintainer status, but could you also add `test` as a required status check in the branch protection settings? Afaik, just checking the "require status checks" option doesn't actually block PRs if it fails

I think I've done that now

**Pull request merged**
