### PR TITLE
add default to exports in package json

### PR DESCRIPTION
**Pull request by premdas26**
I was having trouble with importing from quill-mention in my typescript repo, as described in [this issue](https://github.com/quill-mention/quill-mention/issues/401). Adding the default export in the package.json appears to solve the issue.

### CODE REVIEW

**Comment by premdas26** [comment]
@MadSpindel would you be able to take a look at this? thank you!

**Comment by yadue** [comment]
@MadSpindel can you take a look here?

**Comment by csculley** [comment]
This looks good and I'd like to get it merged in as well, I'm not sure we really need to bump the version for this

**Comment by michaelhamaiev** [comment]
> This looks good and I'd like to get it merged in as well, I'm not sure we really need to bump the version for this Edit: I guess we probably should on second thought

Its look good,
When do you plan to push it?

**Comment by csculley** [comment]
We're working on fixing it but unfortunately we're still dependent on MadSpindel to push new package versions to npm. I think to speed things up, bumping the version and updating the changelog section in the readme in this PR would help with getting it in sooner! Otherwise, we'll need to do that after merging this PR in

**Comment by csculley** [comment]
I have a branch with some in-progress code on that, hopefully I can get around to finishing it sometime soon!

**Comment by MadSpindel** [comment]
@csculley Maybe we/you can test the new GitHub Releases workflow with this PR?

**Comment by csculley** [comment]
I'd be happy to! We just need the publish script merged into master I think

**Comment by MadSpindel** [comment]
> I'd be happy to! We just need the publish script merged into master I think

You mean the Github Workflow? I've merged it already.

**Comment by csculley** [comment]
Okay it should activate automatically whenever the new deployment is triggered! You'll need to change the version in package.json before then though, that should be the only catch

**Pull request merged**
